name: Go CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    - name: Install FFmpeg (includes ffprobe)
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    - name: Verify ffprobe installation
      run: ffprobe -version
    - name: Run tests with coverage
      run: go test -v -coverprofile=coverage.out ./...
